### ISSUE TITLE
Missing 1.12.0 artifact for native targets?

### ISSUE THREAD

**Issue by ankushg** [kosi-libs/MocKMP#49]
Not sure what happened with the publication, but it looks like there's no 1.12.0 artifact for `mockmp-runtime-iossimulatorarm64` or any of the other native targets?

**Comment by benkuly** [comment]
Is there any news here?

Of course this is an open source project, but I think such an important issue should not be ignored. I think a lot of projects use this library. Also open source projects. Because of the nature of KMP, this issue now prevents many other projects from upgrading to Kotlin 1.8. If this project is currently not maintainable, then this should be openly communicated.

**Comment by SalomonBrys** [comment]
Working on it.
Will be fixed very soon

**Comment by SalomonBrys** [comment]
The 1.12.0 missing artefacts have been published.

You are absolutely right @benkuly, this is a critical issue, and I've taken way too long to address it.
All KOSI libs are developed outside of client time, and we need to find a better way to address open-source support.

I'm very sorry it took me so long to correct this, and rest assured that I will try to improve our response and communication.

**Comment by benkuly** [comment]
Thank you very much, it works now :+1: 

I think it's totally okay if something takes longer with an open source project. Next time a short info would just be good, like "We have a lot going on right now, we have it on the screen.".
